name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen libgtest-dev libopencv-dev lcov

    - name: Create build directory and configure project
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Coverage

    - name: Build project
      run: cmake --build build --config Coverage

    - name: Run tests and collect coverage
      run: |
        cd build
        ctest -T Test -T Coverage

    - name: Capture coverage data
      run: |
        cd build
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info

    - name: Display coverage summary
      run: |
        cd build
        lcov --list coverage.info

    - name: Generate HTML report
      run: |
        cd build
        genhtml coverage.info --output-directory coverage-report

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: build/coverage-report
